#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
OS=$(uname -m)
MYIP=$(wget -qO- ipinfo.io/ip)
DOMAIN=$(cat /etc/xray/domain)
ADDR="s/xxxxxxxxx/$DOMAIN/g"

function ovpn_install() {
    rm -rf /etc/openvpn
    mkdir -p /etc/openvpn
    wget -O /etc/openvpn/vpn.zip "https://github.com/hq-mp/pp/raw/refs/heads/main/openvpn/vpn.zip" >/dev/null 2>&1 
    unzip -d /etc/openvpn/ /etc/openvpn/vpn.zip
    rm -f /etc/openvpn/vpn.zip
    chown -R root:root /etc/openvpn/
}

function config_easy() {
    mkdir -p /usr/lib/openvpn/
    cp /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so /usr/lib/openvpn/openvpn-plugin-auth-pam.so
    sed -i 's/#AUTOSTART="all"/AUTOSTART="all"/g' /etc/default/openvpn
    systemctl enable --now openvpn@server-tcp
    systemctl enable --now openvpn@server-udp
    /etc/init.d/openvpn restart
}

function make_follow() {
    echo 1 > /proc/sys/net/ipv4/ip_forward
    sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf

    # TCP
    cat > /etc/openvpn/tcp.ovpn <<-END
client
dev tun
proto tcp
remote xxxxxxxxx 443
resolv-retry infinite
route-method exe
nobind
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 0
END
    sed -i $ADDR /etc/openvpn/tcp.ovpn

    # UDP
    cat > /etc/openvpn/udp.ovpn <<-END
client
dev tun
proto udp
remote xxxxxxxxx 2200
resolv-retry infinite
route-method exe
nobind
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 0
END
    sed -i $ADDR /etc/openvpn/udp.ovpn

    # WS-SSL
    cat > /etc/openvpn/ws-ssl.ovpn <<-END
client
dev tun
proto tcp
remote xxxxxxxxx 443
resolv-retry infinite
route-method exe
nobind
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 0
END
    sed -i $ADDR /etc/openvpn/ws-ssl.ovpn

    # SSL
    cat > /etc/openvpn/ssl.ovpn <<-END
client
dev tun
proto tcp
remote xxxxxxxxx 443
resolv-retry infinite
route-method exe
nobind
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 0
END
    sed -i $ADDR /etc/openvpn/ssl.ovpn
}

function cert_ovpn() {
    echo '<ca>' >> /etc/openvpn/tcp.ovpn
    cat /etc/openvpn/ca.crt >> /etc/openvpn/tcp.ovpn
    echo '</ca>' >> /etc/openvpn/tcp.ovpn

    echo '<ca>' >> /etc/openvpn/udp.ovpn
    cat /etc/openvpn/ca.crt >> /etc/openvpn/udp.ovpn
    echo '</ca>' >> /etc/openvpn/udp.ovpn

    echo '<ca>' >> /etc/openvpn/ws-ssl.ovpn
    cat /etc/openvpn/ca.crt >> /etc/openvpn/ws-ssl.ovpn
    echo '</ca>' >> /etc/openvpn/ws-ssl.ovpn

    echo '<ca>' >> /etc/openvpn/ssl.ovpn
    cat /etc/openvpn/ca.crt >> /etc/openvpn/ssl.ovpn
    echo '</ca>' >> /etc/openvpn/ssl.ovpn

    cp /etc/openvpn/tcp.ovpn /var/www/html/tcp.ovpn
    cp /etc/openvpn/udp.ovpn /var/www/html/udp.ovpn
    cp /etc/openvpn/ws-ssl.ovpn /var/www/html/ws-ssl.ovpn
    cp /etc/openvpn/ssl.ovpn /var/www/html/ssl.ovpn
    cd /var/www/html && zip all-ovpn.zip tcp.ovpn udp.ovpn ws-ssl.ovpn ssl.ovpn >/dev/null 2>&1
}

function install_ovpn() {
    ovpn_install
    config_easy
    make_follow
    cert_ovpn
    systemctl enable --now openvpn
}

install_ovpn
